project:
  type: website
  output-dir: docs

website:
  title: "VIPS"
  navbar:
    search: true
    pinned: true
    right:
      - text: Home
        href: index.qmd
        icon: house-fill
        
      - text: Survival Analysis
        href: ""
        icon: heart-pulse-fill
        menu:
          - text: Introduction to Survival Analysis
            href: pages/survival-intro.qmd
            icon: arrow-bar-right
          - text: Buckley-James Estimator
            href: pages/BJ-estimator.qmd
            icon: arrow-bar-right
            
      - text: About
        href: about.qmd
        icon: info-circle-fill
        

format:
  html:
    ## Toc options
    toc: true
    toc-title: Contents
    toc-location: right
    toc-expand: 2 ## true = all options, false = non
    ## Sections
    number-sections: true
    number-depth: 3
    anchor-sections: true
    smooth-scroll: true
    ## math and style
    theme: cosmo
    html-math-method: katex
    css: styles.css
    linkcolor: rgb(214, 122, 127)
    ## citation options
    citations-hover: true
    footnotes-hover: true
    crossrefs-hover: true
    ## External links
    link-external-icon: true
    link-external-newwindow: true
    ## codes
    code-fold: true
    code-overflow: wrap
    ## width
    grid: 
      sidebar-width:	250px ## left panel
      body-width:	1000px     ## middle panel
      margin-width:	250px   ## right panel
      gutter-width:	2.5em   ## left-right-extreme space



